name: build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-tests:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,  macOS-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows-release
            build-type: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10.6
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'f14984af3738e69f197bf0e647a8dca12de92996'

      - name: Configure CMake
        run: |
          cmake -S . -B make -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}
          
      - name: Build
        working-directory: ./make
        run: |
          rm -rf ../vcpkg/buildtrees
          rm -rf ../vcpkg/downloads
          cmake --build . --config ${{ matrix.build-type }} --parallel $(nproc)
